language: cpp
os:
  - linux
dist: bionic

compiler:
  - gcc

env:
  - NATURE=Debug
  - NATURE=Release

addons:
  apt:
    packages:
      - git
      - curl
      - wget
      - python
      - sudo
      - lsb-release
      - ninja-build

script:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then ./buildstrap-${NATURE}.sh; fi